import threading
from Crypto.Hash import SHA256,SHA1,SHA224,SHA384,SHA512

TOTAL_NODES = 10
PROF_OF_WORK_ZEROS = 3
MINING_REWARD = 10
CONFIRMATION_BLOCK = 1
MARKEL_TREE_ARITY = 2
SIMULATION_TIME = 60
WAIT_BEFORE_NEW_TRX = 2
BLOCK_CREATION_TIME = 7
CRYPTO_METHOD = SHA256

nodeInfo ={}
nodePublicKeyToId = {}
commonDataLock = threading.Lock()


class MSG():
    MINE_BLOCK = 0
    PERFORM_TRX = 1
    RECEIVE_BLOCK = 2
    BROADCAST_PUBLIC_KEY = 3
    BROADCAST_GENESIS_BLOCK = 4
